import type { Locale } from "@/lib/locale"

export const COPY = {
  en: {
    brand: "Arab Pro Academy",
    city: "Riyadh",
    enroll: "Enroll Now",
    nav: {
      about: "About",
      courses: "Courses",
      online: "Online",
      pricing: "Pricing",
      placement: "Placement",
      faq: "FAQ",
      contact: "Contact",
    },
    hero: {
      certified: "Certified",
      badge: "Now Enrolling — Riyadh, KSA",
      titleLead: "Master",
      titleGold: "Spoken Arabic",
      titleRest: "in Just 3 Months",
      body: "Spoken Arabic classes for non-native speakers — Indian professionals, GCC expats, and beginners in Riyadh. In-person or live online. Speak with confidence in 3 months.",
      tagline: "أكاديمية العرب برو — ابدأ رحلتك اليوم",
      ctaPricing: "View Pricing & Enroll",
      ctaWhatsapp: "WhatsApp Us",
      placement: "Not sure of your level? Take the 2-minute placement quiz →",
    },
    why: {
      eyebrow: "Why Learn Arabic",
      title: "Your Career Deserves",
      titleGold: "This Advantage",
      body: "Whether you work in Saudi Arabia, the UAE, Qatar, or Kuwait — or join live online from India — spoken Arabic is the skill that moves careers and daily life forward.",
    },
    courses: {
      eyebrow: "What You Get",
      title: "A Complete Program,",
      titleGold: "Built for Results",
      body: "Everything you need to go from hesitant beginner to confident Arabic speaker — guaranteed.",
      pathBadge: "3-Month Learning Path",
      pathTitle: "Your Journey to Fluency",
      guaranteed: "Guaranteed outcomes",
    },
    online: {
      subtitle: "Spoken Arabic Program for Expats in Saudi Arabia",
      badge: "New Online Courses • Beginner & Intermediate Levels",
      choose: "Choose Your Level",
      chooseBody: "Two brand-new 8-week online tracks — pick the one that fits you",
      perMonth: "per month",
      fullCourse: "full course — 2 months (8 weeks)",
      enroll: "Enroll via WhatsApp",
      included: "What’s Included",
      getInTouch: "Get In Touch",
      callWhatsapp: "Call / WhatsApp:",
      scan: "Scan to WhatsApp us",
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Invest in Your",
      titleGold: "Arabic Fluency",
      body: "Simple, transparent pricing. Most students choose the 3-month package — it’s the complete journey to confident spoken Arabic and saves you 798 SAR.",
      popular: "Most Popular",
      save: "Best value — save 798 SAR vs monthly",
      footnote: "Prices in Saudi Riyal (SAR). Limited seats per batch — reserve yours today.",
    },
    audience: {
      eyebrow: "Who Is It For",
      title: "Built for Every",
      titleGold: "Ambitious Learner",
      body: "Whether you’re advancing your career, starting fresh in Riyadh, or seeking deeper cultural connection — our program adapts to your goal.",
    },
    testimonials: {
      eyebrow: "Success Stories",
      title: "Real Students,",
      titleGold: "Real Results",
      rating: "4.9/5 from enrolled students in Riyadh",
    },
    faq: {
      eyebrow: "Questions",
      title: "Frequently Asked",
      titleGold: "Questions",
    },
    contact: {
      eyebrow: "Get In Touch",
      title: "Start Your Arabic",
      titleGold: "Journey Today",
      body: "Have a question or ready to enroll? Reach out — we respond within minutes during business hours.",
      whatsappHint: "Fastest response — chat with us now",
      call: "Call Us",
      callHint: "Speak with our admissions team",
      emailHint: "We reply within 24 hours",
      locationHint: "In-person & online classes available",
      formTitle: "Request a Callback",
      formBody: "Fill this form and we’ll call you back with batch details and pricing.",
      name: "Full Name",
      namePh: "Your full name",
      phone: "Phone Number",
      interest: "Interested In",
      sending: "Saving…",
      send: "Send via WhatsApp",
      noSpam: "No spam. We only call to discuss your enrollment.",
      error: "Name and phone are required.",
      question: "Just have a question",
      onlinePrefix: "Online",
      perMonthShort: "SAR/month",
    },
    footer: {
      blurb:
        "Helping expats, students, and professionals master spoken Arabic and accelerate their careers across Saudi Arabia and the Gulf.",
      seoLine:
        "Spoken Arabic classes in Riyadh for non-native speakers. Live online for learners in the UAE, Qatar, Kuwait, Bahrain, Oman, and India.",
      links: "Quick Links",
      why: "Why Learn Arabic",
      courseDetails: "Course Details",
      onlineLevels: "Online Levels",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact Us",
      rights: "All rights reserved.",
      tagline: "أكاديمية العرب برو — تعلم العربية بثقة",
    },
    placement: {
      eyebrow: "2-minute check",
      title: "Spoken Arabic placement",
      body: "No grammar exam. This tells us whether Beginner or Intermediate fits you. After you finish, WhatsApp us to enroll — we do not use a long checkout.",
      unavailable: "The quiz is not live yet. Message us and we will place you in class.",
      whatsapp: "WhatsApp the academy",
      result: "Your result",
      recommended: "Recommended:",
      beginner: "Beginner / 3-month spoken",
      intermediate: "Online Intermediate",
      confirm: "The teacher will confirm on a short WhatsApp voice chat.",
      enroll: "Enroll on WhatsApp",
      pricing: "See pricing",
      name: "Your name",
      phone: "WhatsApp number",
      submit: "See my level",
      back: "← Back to Arab Pro Academy",
      waMessage: (score: number, total: number, level: string) =>
        `Hi, I took the placement quiz (${score}/${total}) and was placed at ${level}. I want to enroll.`,
    },
    switchToAr: "العربية",
    switchToEn: "EN",
    switchAria: "Switch language",
  },
  ar: {
    brand: "أكاديمية عرب برو",
    city: "الرياض",
    enroll: "سجّل الآن",
    nav: {
      about: "لماذا العربية",
      courses: "الدورات",
      online: "أونلاين",
      pricing: "الأسعار",
      placement: "تحديد المستوى",
      faq: "أسئلة",
      contact: "تواصل",
    },
    hero: {
      certified: "معتمد",
      badge: "التسجيل مفتوح — الرياض، السعودية",
      titleLead: "أتقن",
      titleGold: "العربية المحكية",
      titleRest: "خلال 3 أشهر فقط",
      body: "برنامج للمقيمين غير الناطقين بالعربية — المهنيون من الهند والخليج والمبتدئون في الرياض. حضوري أو أونلاين مباشر. تحدّث بثقة خلال 3 أشهر.",
      tagline: "أكاديمية العرب برو — ابدأ رحلتك اليوم",
      ctaPricing: "شاهد الأسعار وسجّل",
      ctaWhatsapp: "واتساب",
      placement: "غير متأكد من مستواك؟ اختبر تحديد المستوى خلال دقيقتين ←",
    },
    why: {
      eyebrow: "لماذا تتعلم العربية",
      title: "مسارك المهني يستحق",
      titleGold: "هذا التميّز",
      body: "سواء تعمل في السعودية أو الإمارات أو قطر أو الكويت — أو تنضم أونلاين من الهند — العربية المحكية هي المهارة التي تحرّك المسار المهني والحياة اليومية.",
    },
    courses: {
      eyebrow: "ماذا تحصل عليه",
      title: "برنامج متكامل،",
      titleGold: "مصمّم للنتائج",
      body: "كل ما تحتاجه لتنتقل من مبتدئ متردد إلى متحدّث واثق — مع ضمان.",
      pathBadge: "مسار 3 أشهر",
      pathTitle: "رحلتك نحو الطلاقة",
      guaranteed: "نتائج مضمونة",
    },
    online: {
      subtitle: "برنامج العربية المحكية للمقيمين في السعودية",
      badge: "دورات أونلاين جديدة • مبتدئ ومتوسط",
      choose: "اختر مستواك",
      chooseBody: "مساران أونلاين لمدة 8 أسابيع — اختر ما يناسبك",
      perMonth: "شهرياً",
      fullCourse: "الدورة كاملة — شهران (8 أسابيع)",
      enroll: "التسجيل عبر واتساب",
      included: "ما الذي يشمله البرنامج",
      getInTouch: "تواصل معنا",
      callWhatsapp: "اتصال / واتساب:",
      scan: "امسح للتواصل عبر واتساب",
    },
    pricing: {
      eyebrow: "الأسعار",
      title: "استثمر في",
      titleGold: "طلاقتك بالعربية",
      body: "أسعار واضحة. معظم الطلاب يختارون باقة 3 أشهر — الرحلة الكاملة للعربية المحكية بثقة، وتوفّر 798 ريالاً.",
      popular: "الأكثر اختياراً",
      save: "أفضل قيمة — وفّر 798 ريالاً مقارنة بالشهري",
      footnote: "الأسعار بالريال السعودي. المقاعد محدودة في كل دفعة — احجز مقعدك اليوم.",
    },
    audience: {
      eyebrow: "لمن هذا البرنامج",
      title: "مصمّم لكل",
      titleGold: "متعلّم طموح",
      body: "سواء تطوّر مسيرتك، أو بدأت حياة جديدة في الرياض، أو تبحث عن ارتباط ثقافي أعمق — البرنامج يتكيّف مع هدفك.",
    },
    testimonials: {
      eyebrow: "قصص نجاح",
      title: "طلاب حقيقيون،",
      titleGold: "نتائج حقيقية",
      rating: "4.9/5 من طلابنا في الرياض",
    },
    faq: {
      eyebrow: "أسئلة",
      title: "الأسئلة",
      titleGold: "الشائعة",
    },
    contact: {
      eyebrow: "تواصل معنا",
      title: "ابدأ رحلتك مع",
      titleGold: "العربية اليوم",
      body: "سؤال أو جاهز للتسجيل؟ راسلنا — نرد خلال دقائق في أوقات العمل.",
      whatsappHint: "أسرع رد — تحدّث معنا الآن",
      call: "اتصل بنا",
      callHint: "تحدث مع فريق القبول",
      emailHint: "نرد خلال 24 ساعة",
      locationHint: "حصص حضورية وأونلاين",
      formTitle: "اطلب اتصالاً راجعاً",
      formBody: "عبّئ النموذج وسنتصل بك بمواعيد الدفعات والأسعار.",
      name: "الاسم الكامل",
      namePh: "اسمك الكامل",
      phone: "رقم الجوال",
      interest: "مهتم بـ",
      sending: "جاري الحفظ…",
      send: "إرسال عبر واتساب",
      noSpam: "بدون إزعاج. نتصل فقط لمناقشة التسجيل.",
      error: "الاسم والجوال مطلوبان.",
      question: "لدي سؤال فقط",
      onlinePrefix: "أونلاين",
      perMonthShort: "ريال/شهر",
    },
    footer: {
      blurb:
        "نساعد المقيمين والطلاب والمهنيين على إتقان العربية المحكية وتسريع مسيرتهم في السعودية والخليج.",
      seoLine:
        "دورات عربية محكية في الرياض لغير الناطقين بها. أونلاين مباشر للمتعلمين في الإمارات وقطر والكويت والبحرين وعُمان والهند.",
      links: "روابط سريعة",
      why: "لماذا العربية",
      courseDetails: "تفاصيل الدورة",
      onlineLevels: "المستويات الأونلاين",
      privacy: "سياسة الخصوصية",
      terms: "الشروط",
      contact: "تواصل معنا",
      rights: "جميع الحقوق محفوظة.",
      tagline: "أكاديمية العرب برو — تعلم العربية بثقة",
    },
    placement: {
      eyebrow: "اختبار دقيقتين",
      title: "تحديد مستوى العربية المحكية",
      body: "ليس اختبار نحو. يساعدنا لمعرفة إن كان المبتدئ أو المتوسط أنسب لك. بعد النتيجة سجّل عبر واتساب — بدون دفع إلكتروني طويل.",
      unavailable: "الاختبار غير متاح الآن. راسلنا وسنحدد مستواك.",
      whatsapp: "واتساب الأكاديمية",
      result: "نتيجتك",
      recommended: "المستوى المقترح:",
      beginner: "مبتدئ / الدورة الحضورية 3 أشهر",
      intermediate: "أونلاين — متوسط",
      confirm: "المعلم يؤكد المستوى بمكالمة واتساب صوتية قصيرة.",
      enroll: "التسجيل عبر واتساب",
      pricing: "شاهد الأسعار",
      name: "اسمك",
      phone: "رقم واتساب",
      submit: "اعرض مستواي",
      back: "العودة إلى أكاديمية عرب برو ←",
      waMessage: (score: number, total: number, level: string) =>
        `مرحباً، أنهيت اختبار تحديد المستوى (${score}/${total}) ومستواي المقترح: ${level}. أرغب بالتسجيل.`,
    },
    switchToAr: "العربية",
    switchToEn: "EN",
    switchAria: "تغيير اللغة",
  },
} as const

export type Copy = (typeof COPY)["en"]

export function getCopy(locale: Locale): Copy {
  return COPY[locale] as Copy
}
