export type WeekSeed = {
  weekNumber: number
  title: string
  outcomes: string
  vocabulary: string
  activity: string
  homework: string
}

export const IN_PERSON_WEEKS: WeekSeed[] = [
  {
    weekNumber: 1,
    title: "Sounds, greetings, and your name",
    outcomes: "Greet someone, introduce yourself, say where you are from.",
    vocabulary: "hello / peace\nmy name is\nfrom\nI am\nplease\nthank you",
    activity: "Pair greetings around the room. Swap names three times.",
    homework: "Voice note (30s): greet and say your name and country.",
  },
  {
    weekNumber: 2,
    title: "Numbers, time, and days",
    outcomes: "Count 1–20, tell the time, say which day you have class.",
    vocabulary: "one–twenty\ntoday\ntomorrow\nhour\nmorning\nevening",
    activity: "Role-play: ask what time the next class starts.",
    homework: "Voice note: say three times of day you use Arabic this week.",
  },
  {
    weekNumber: 3,
    title: "Family and simple questions",
    outcomes: "Ask who someone is, talk about family in one or two sentences.",
    vocabulary: "father\nmother\nbrother\nsister\nwho\nwhere\nhow many",
    activity: "Show a family photo (or sketch) and answer classmate questions.",
    homework: "Voice note: introduce two family members.",
  },
  {
    weekNumber: 4,
    title: "Getting around Riyadh",
    outcomes: "Ask for directions, understand left/right/straight, name common places.",
    vocabulary: "left\nright\nstraight\nnear\nmosque\nmarket\nhospital",
    activity: "Map role-play: get from the academy to a supermarket.",
    homework: "Voice note: give directions from your home to a nearby shop.",
  },
  {
    weekNumber: 5,
    title: "Shopping and prices",
    outcomes: "Ask the price, bargain politely, say you will take it or not.",
    vocabulary: "how much\nexpensive\ncheap\nI want\nthis\nthat\nriyal",
    activity: "Classroom souq: teacher is the seller, students buy three items.",
    homework: "Voice note: buy fruit — ask price, then say too expensive.",
  },
  {
    weekNumber: 6,
    title: "Food, cafes, and orders",
    outcomes: "Order food and drink, say likes/dislikes, ask for the bill.",
    vocabulary: "water\ncoffee\ntea\nbread\nchicken\nbill\nwithout",
    activity: "Cafe role-play in pairs. One waiter, one customer.",
    homework: "Voice note: order breakfast for two people.",
  },
  {
    weekNumber: 7,
    title: "Transport and appointments",
    outcomes: "Book a ride, say you are late, reschedule a simple appointment.",
    vocabulary: "taxi\ncar\nwait\nlate\nnow\nlater\nappointment",
    activity: "Phone call drill: you will be 10 minutes late to class.",
    homework: "Voice note: call to move an appointment to tomorrow.",
  },
  {
    weekNumber: 8,
    title: "Home, neighbours, daily life",
    outcomes: "Talk about your building, ask a neighbour for help, describe your day.",
    vocabulary: "house\nflat\nneighbour\nkey\nhelp\ntoday I…",
    activity: "Neighbour knock: borrow sugar / ask about the water tank.",
    homework: "Voice note: describe your typical weekday in 5 sentences.",
  },
  {
    weekNumber: 9,
    title: "Workplace small talk",
    outcomes: "Greet colleagues, ask how work is going, talk about a simple task.",
    vocabulary: "office\nmeeting\nmanager\ncolleague\nbusy\nfinished",
    activity: "Stand-up meeting: each student reports one task in Arabic.",
    homework: "Voice note: tell your manager you finished a task.",
  },
  {
    weekNumber: 10,
    title: "Phone calls and messages",
    outcomes: "Answer the phone, leave a short message, confirm a number.",
    vocabulary: "hello (phone)\nspeaking\ncall back\nmessage\nnumber\nwrong",
    activity: "Missed-call role-play: leave a 20-second voicemail.",
    homework: "Voice note: leave a message asking someone to call you.",
  },
  {
    weekNumber: 11,
    title: "Meetings and polite disagreement",
    outcomes: "Agree, disagree politely, ask to repeat, summarise a simple point.",
    vocabulary: "I agree\nI don’t agree\nplease repeat\nin my opinion\nbecause",
    activity: "Mini meeting: choose a time for a team lunch. Disagree once.",
    homework: "Voice note: disagree politely with a suggested meeting time.",
  },
  {
    weekNumber: 12,
    title: "Fluency check — real conversations",
    outcomes: "Hold a 3-minute everyday conversation without switching to English.",
    vocabulary: "Revision of weeks 1–11. Student’s own workplace words.",
    activity: "Final oral: market + office + introductions. Rubric scored 1–5.",
    homework: "None — oral exam in class. Free extension if they do not pass.",
  },
]

export const ONLINE_BEGINNER_WEEKS: WeekSeed[] = [
  {
    weekNumber: 1,
    title: "Alphabet sounds and greetings",
    outcomes: "Produce key sounds, greet, say your name.",
    vocabulary: "hello\nwelcome\nmy name\nhow are you\nfine",
    activity: "Live drill: repeat after teacher, then pair in breakout.",
    homework: "Voice note: greet and say your name.",
  },
  {
    weekNumber: 2,
    title: "Numbers and classroom phrases",
    outcomes: "Count 1–10, say I don’t understand, please repeat.",
    vocabulary: "one–ten\nplease repeat\nslowly\nI don’t understand",
    activity: "Teacher says a number; students type it in chat then say it.",
    homework: "Voice note: count 1–10 and ask the teacher to repeat.",
  },
  {
    weekNumber: 3,
    title: "Introductions and countries",
    outcomes: "Say where you live and work in one sentence.",
    vocabulary: "I live in\nI work in\nRiyadh\nIndia\nPakistan\nPhilippines",
    activity: "Speed intros: 20 seconds each on camera.",
    homework: "Voice note: I live in … I work in …",
  },
  {
    weekNumber: 4,
    title: "Family and yes/no questions",
    outcomes: "Ask simple yes/no questions about family.",
    vocabulary: "do you have\nchildren\nhusband\nwife\nyes\nno",
    activity: "Interview a classmate about their family.",
    homework: "Voice note: three sentences about your family.",
  },
  {
    weekNumber: 5,
    title: "Shopping phrases",
    outcomes: "Ask how much, say this please.",
    vocabulary: "how much\nthis\nthat\nplease\nI want",
    activity: "Virtual shop: teacher shows objects on camera.",
    homework: "Voice note: buy two items and ask the price.",
  },
  {
    weekNumber: 6,
    title: "Food and drinks",
    outcomes: "Order a drink and a meal.",
    vocabulary: "water\ncoffee\ntea\nrice\nchicken\nbill",
    activity: "Cafe order in pairs (breakout).",
    homework: "Voice note: order lunch.",
  },
  {
    weekNumber: 7,
    title: "Directions near you",
    outcomes: "Understand left, right, near, far.",
    vocabulary: "left\nright\nnear\nfar\nstraight",
    activity: "Describe the way from your door to the street.",
    homework: "Voice note: directions to the nearest mosque or shop.",
  },
  {
    weekNumber: 8,
    title: "Beginner conversation check",
    outcomes: "2-minute chat: greet, name, work, one shopping line.",
    vocabulary: "Revision weeks 1–7",
    activity: "Oral check with teacher (breakout, 4 minutes each).",
    homework: "None — oral check in the live class.",
  },
]

export const ONLINE_INTERMEDIATE_WEEKS: WeekSeed[] = [
  {
    weekNumber: 1,
    title: "Review and workplace greetings",
    outcomes: "Greet colleagues and start a short work chat.",
    vocabulary: "good morning\nhow is work\nbusy\nlater",
    activity: "Office corridor role-play.",
    homework: "Voice note: greet a colleague and ask about their day.",
  },
  {
    weekNumber: 2,
    title: "Phone calls",
    outcomes: "Answer, ask who is speaking, take a simple message.",
    vocabulary: "who is speaking\nplease wait\nI will tell him\ncall back",
    activity: "Missed call + voicemail drill.",
    homework: "Voice note: take a message for your manager.",
  },
  {
    weekNumber: 3,
    title: "Appointments and being late",
    outcomes: "Reschedule and apologise for delay.",
    vocabulary: "sorry\nlate\ntomorrow\nsame time\npossible",
    activity: "Call the clinic to move an appointment.",
    homework: "Voice note: you will be 15 minutes late.",
  },
  {
    weekNumber: 4,
    title: "Shopping with negotiation",
    outcomes: "Bargain politely and walk away if needed.",
    vocabulary: "expensive\ncheap\nlast price\nI’ll think\nthank you",
    activity: "Souq negotiation in pairs.",
    homework: "Voice note: negotiate a price then refuse.",
  },
  {
    weekNumber: 5,
    title: "Meetings — agree and disagree",
    outcomes: "Give an opinion and disagree without sounding rude.",
    vocabulary: "I think\nbecause\nI agree\nI don’t agree\nmaybe",
    activity: "Choose a restaurant for a team dinner.",
    homework: "Voice note: disagree with a suggested time.",
  },
  {
    weekNumber: 6,
    title: "Explaining a problem",
    outcomes: "Describe a simple work or home problem and ask for help.",
    vocabulary: "problem\nbroken\nnot working\nhelp\nplease check",
    activity: "Call maintenance about AC / water.",
    homework: "Voice note: explain a problem at home.",
  },
  {
    weekNumber: 7,
    title: "Stories about your week",
    outcomes: "Past-time phrases: yesterday, last week, I went, I did.",
    vocabulary: "yesterday\nlast week\nI went\nI did\nthen",
    activity: "Weekend story, 1 minute each.",
    homework: "Voice note: what you did last Friday.",
  },
  {
    weekNumber: 8,
    title: "Intermediate fluency check",
    outcomes: "3-minute conversation: work + daily life without English.",
    vocabulary: "Revision weeks 1–7",
    activity: "Oral exam with rubric (pronunciation, vocab, fluency, understanding).",
    homework: "None — oral exam in the live class.",
  },
]
